#!/bin/sh

cat <<EOF
This is a STI jetty builder image responsible for consuming a JEE project
and deploying it onto jetty server.

This image is built from https://github.com/memeinstigator/appformer-sti-jetty-builder
You can use this image in Openshift 3 as the builder image and pass in AppPackage github url

If war or exploded folders are present in <AppPackage Git URL>/engine/helloworld they will be copied
into the jetty deployments directory as is.


--------------------------------------------------------
To create an STI image outside of OpenShift3:
#install GO - you can install on any machine. 
#For later steps you need docker as well. If you dont have it, install it too. "yum -y install docker"
yum -y install go
 
#Reference: http://golang.org/doc/code.html
#Config for GO tool
# Home can be set your default home dir, it is not already set
mkdir $HOME/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin


To use it, install STI: 
# Get STI tool
$ go get github.com/openshift/source-to-image
$ cd ${GOPATH}/src/github.com/openshift/source-to-image
$ export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/go/bin/
$ hack/build-go.sh
 
#Now you should have 'sti build' command working.
#Run STI build outside OpenShift3
sti build https://github.com/memeinstigator/HelloWorldAppPackage appformer-sti-jetty-builder my-helloworld-jetty-image --loglevel=5 --context-dir=engine/helloworld

----------------------------------------------------------

Run
You can then run the resulting image via:
docker run -d -p 8080:8080 -name="my-helloworld-jetty-container" my-helloworld-jetty-image
curl http://localhost:8080/HelloWorld2/index.jsp

EOF
